export enum StudentWSEvent {
  JOIN_CLASS = "EVENT_STUDENT_JOIN_CLASS",
  STREAM_CONNECT = "EVENT_STUDENT_STREAM_CONNECT",
  MUTE_AUDIO = "EVENT_STUDENT_MUTE_AUDIO",
  MUTE_VIDEO = "EVENT_STUDENT_MUTE_VIDEO",
  LEAVE = "EVENT_STUDENT_LEAVE",
  DISCONNECT = "EVENT_STUDENT_DISCONNECT",

  STUDENT_RAISING_HAND = "EVENT_STUDENT_RAISING_HAND",
  STUDENT_LIKE = "EVENT_STUDENT_LIKE",
}
